#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker1"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "9b740dbaa629481997b2fd22a98e56cc" }
]
